### ISSUE TITLE
[PE-D] Unable to add lesson outside of 0800-2200

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-3/tp#272] opened 2021-10-30 09:38 UTC
Is there a specific reason why you are imposing this restriction on users? I feel like the user should have the freedom to decide when to conduct their lessons. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ganhongyao/ped#11

**Comment by lingshanng** [comment] 2021-10-30 14:50
duplicate of https://github.com/AY2122S1-CS2103T-F13-3/tp/issues/243

**Closed by lingshanng** 2021-10-30 14:50 UTC
